# Generated by Django 5.0.7 on 2024-07-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('inscription_data', models.DateField()),
                ('photo', models.ImageField(upload_to='posts/covers/%y/%m/%d')),
            ],
        ),
    ]
