# Generated by Django 5.0.7 on 2024-07-18 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='posts/covers/%y/%m/%d')),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='inscription_data',
            new_name='inscription_date',
        ),
        migrations.AddField(
            model_name='student',
            name='matricula',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='turma',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='cadastroaluno.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='cadastroaluno.teacher'),
        ),
    ]
