# Generated by Django 5.0.7 on 2024-07-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0005_remove_class_teacher_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='moderator',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='cadastroaluno.moderator'),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='student',
            name='moderator',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='cadastroaluno.moderator'),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='teacher',
            name='moderator',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='cadastroaluno.moderator'),
            preserve_default=1,
        ),
    ]
