# Generated by Django 5.0.7 on 2024-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0006_class_moderator_student_moderator_teacher_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/covers/%y/%m/%d'),
        ),
    ]
