# Generated by Django 5.0.7 on 2024-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0010_remove_teacher_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
