# Generated by Django 5.0.7 on 2024-07-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0011_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.IntegerField(),
        ),
    ]
