# Generated by Django 5.0.7 on 2024-08-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroaluno', '0013_student_user_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator_Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='cadastroaluno.moderator')),
            ],
        ),
    ]
